#!/usr/bin/env python3
"""Generate the small native Aurora font atlas used by the GUI shell.

The kernel never parses a font file.  This build-time tool converts a
redistributable host font into fixed-cell, 8-bit alpha glyph masks.
"""
from pathlib import Path
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "kernel" / "drivers" / "aurora_font_atlas.h"
FONT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(
    "/usr/share/fonts/TTF/DejaVuSans.ttf"
)
SIZES = (12, 14, 16, 20, 24, 32)
FIRST, COUNT = 32, 95


def byte_rows(image, cell):
    row_bytes = (cell + 7) // 8
    out = []
    pix = image.load()
    for y in range(cell):
        for block in range(row_bytes):
            value = 0
            for bit in range(8):
                x = block * 8 + bit
                if x < cell:
                    if pix[x, y] >= 128:
                        value |= 1 << (7 - bit)
            out.append(value)
    return out


def cbytes(values):
    return ", ".join(f"0x{v:02X}" for v in values)


def main():
    if not FONT.exists():
        raise SystemExit(f"font not found: {FONT}")
    lines = [
        "/* Generated by tools/gen_aurora_assets.py; do not edit by hand. */",
        "#pragma once",
        "#include <stdint.h>",
        "typedef struct { uint16_t cell, row_bytes; const uint8_t *bits;",
        "    const uint8_t *widths; } aurora_font_size_t;",
    ]
    tables = []
    for size in SIZES:
        font = ImageFont.truetype(str(FONT), size)
        row_bytes = (size + 7) // 8
        data, widths = [], []
        for code in range(FIRST, FIRST + COUNT):
            char = chr(code)
            bbox = font.getbbox(char)
            advance = int(round(font.getlength(char)))
            widths.append(max(1, min(size, advance)))
            image = Image.new("L", (size, size), 0)
            draw = ImageDraw.Draw(image)
            # Keep the visible glyph left-bearing aligned with its logical
            # advance.  Centering each glyph in the cell while the renderer
            # advances by the glyph width makes narrow letters (i/l/t) appear
            # to drift and collide with the following character.
            bx0, by0, bx1, by1 = bbox
            tw, th = bx1 - bx0, by1 - by0
            ox = max(0, -bx0)
            oy = max(0, (size - th) // 2 - by0)
            draw.text((ox, oy), char, font=font, fill=255)
            data.extend(byte_rows(image, size))
        name = f"aurora_font_{size}"
        lines.append(f"static const uint8_t {name}_bits[] = {{")
        for pos in range(0, len(data), 16):
            lines.append("    " + cbytes(data[pos:pos + 16]) + ",")
        lines.append("};")
        lines.append(f"static const uint8_t {name}_widths[] = {{")
        lines.append("    " + cbytes(widths) + "");
        lines.append("};")
        tables.append((size, row_bytes, name))
    lines.append("static const aurora_font_size_t aurora_font_sizes[] = {")
    for size, row_bytes, name in tables:
        lines.append(f"    {{{size}, {row_bytes}, {name}_bits, {name}_widths}},")
    lines.append("};")
    lines.append(f"#define AURORA_FONT_SIZE_COUNT {len(SIZES)}")
    lines.append(f"#define AURORA_FONT_FIRST {FIRST}")
    lines.append(f"#define AURORA_FONT_COUNT {COUNT}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"generated {OUT} from {FONT}")


if __name__ == "__main__":
    main()
